from typing import Any
from docker.models.images import Image

class Container:
    id: str
    name: str
    status: str
    image: Image
    attrs: dict[str, Any]

    def start(self, **kwargs: Any) -> None: ...
    def stop(self, **kwargs: Any) -> None: ...
    def restart(self, **kwargs: Any) -> None: ...
    def kill(self, **kwargs: Any) -> None: ...
    def remove(self, **kwargs: Any) -> None: ...
    def pause(self, **kwargs: Any) -> None: ...
    def unpause(self, **kwargs: Any) -> None: ...
